apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: curl-test
  labels:
    k8s-app: curl-test
spec:
  selector:
    matchLabels:
      name: curl-test
  template:
    metadata:
      labels:
        name: curl-test
    spec:
      containers:
      - name: curl-test
        image: gcr.io/scenic-rampart-237010/ping-app:v0.1
        envFrom:
        - configMapRef:
          name: special-config
        command: ["/bin/sh", "-c"]
        args: ["bash root/pingscript.sh $(PINGTIME) $(IPTARGET) $(PORTTARGET)"]
